title: checkra1n
logo: /checkra1n.jpg
description: This is a repository for the checkra1n jailbreak.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
favicon: /favicon.ico
<link rel="shortcut icon" type="image/x-icon" href="{{ "/favicon.ico" | prepend:ifixerpro.github.io/checkra1n}}" >
